# Generated by Django 3.0.6 on 2020-05-21 19:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('permission', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.BigIntegerField()),
                ('created_dt', models.DateTimeField()),
                ('questions', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CodingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_id', models.BigIntegerField(db_index=True)),
                ('policy_instance_id', models.BigIntegerField(db_index=True)),
                ('coding_id', models.BigIntegerField(db_index=True)),
                ('created_dt', models.DateTimeField()),
                ('coding_values', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('alexa_rank', models.BigIntegerField()),
                ('policy_type', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_scan_dt', models.DateTimeField()),
                ('scan_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.BigIntegerField(db_index=True)),
                ('scan_dt', models.DateTimeField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RawPolicy_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.BigIntegerField(db_index=True)),
                ('raw_content', models.TextField()),
                ('capture_date', models.DateField()),
                ('capture_source', models.TextField()),
            ],
        ),
    ]
