# Generated by Django 3.0.6 on 2020-05-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RawPolicy_instance',
            new_name='RawPolicyInstance',
        ),
    ]
