# Generated by Django 3.0.6 on 2020-05-22 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200521_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='codinginstance',
            name='created_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='last_scan_dt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='scan_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='policyinstance',
            name='scan_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rawpolicyinstance',
            name='capture_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
