# Generated by Django 3.0.6 on 2020-05-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200522_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='codinginstance',
            unique_together={('coder_id', 'policy_instance_id')},
        ),
    ]
