# Generated by Django 3.0.6 on 2020-06-06 23:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200525_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='url',
        ),
        migrations.AddField(
            model_name='policy',
            name='urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterUniqueTogether(
            name='codinginstance',
            unique_together={('coder_email', 'coding_id', 'policy_instance_id')},
        ),
    ]
