# Generated by Django 3.0.6 on 2020-06-14 20:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_policy_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyinstance',
            name='raw_policy_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='policy',
            name='urls',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
