# Generated by Django 3.0.6 on 2020-06-14 20:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200614_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawpolicyinstance',
            name='raw_content',
        ),
        migrations.AddField(
            model_name='rawpolicyinstance',
            name='raw_content_blocks',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
