# Generated by Django 3.0.6 on 2020-06-25 06:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200619_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_email', models.CharField(max_length=255)),
                ('coding_id', models.BigIntegerField()),
                ('policy_instance_id', models.BigIntegerField()),
                ('question_timings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('session_timing', django.contrib.postgres.fields.jsonb.JSONField()),
                ('session_identifier', models.BigIntegerField()),
            ],
        ),
    ]
