# Generated by Django 3.0.6 on 2020-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_timingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingsession',
            name='session_identifier',
            field=models.BigIntegerField(unique=True),
        ),
    ]
