# Generated by Django 3.2.3 on 2021-05-19 01:01

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_coder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('coder_email', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
                ('notes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_dt', models.DateTimeField(null=True)),
                ('type', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
