# Generated by Django 3.2.3 on 2021-05-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_assignment_assignmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coding',
            name='questions',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='codinginstance',
            name='coding_values',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='policy',
            name='categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='policy',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='policy',
            name='urls',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='policyinstance',
            name='content',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='rawpolicyinstance',
            name='raw_content_blocks',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='timingsession',
            name='question_timings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='timingsession',
            name='session_timing',
            field=models.JSONField(),
        ),
    ]
