# Generated by Django 3.2.3 on 2021-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_project_project_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='meta',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='coding',
            name='questions',
            field=models.JSONField(default=[]),
        ),
    ]
