# Generated by Django 3.2.3 on 2021-05-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210523_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='coding',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
