# Generated by Django 3.2.3 on 2021-05-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_project_project_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coding',
            old_name='questions',
            new_name='categories',
        ),
    ]
