# Generated by Django 3.2.3 on 2021-05-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210531_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='progress',
            field=models.JSONField(default=dict),
        ),
    ]
