# Generated by Django 3.2.3 on 2021-06-02 23:48
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0028_policy_progress'),
    ]
    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_prefix',
            new_name='prefix',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_settings',
            new_name='settings',
        ),
    ]
