# Generated by Django 3.2.4 on 2021-06-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210602_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='KVStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.BigIntegerField(default=1)),
                ('k', models.CharField(db_index=True, max_length=255)),
                ('v', models.JSONField(default=dict)),
            ],
        ),
    ]
