# Generated by Django 4.1.2 on 2022-10-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_kvstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coding',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='codinginstance',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policyinstance',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timingsession',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
