# Generated by Django 3.2.6 on 2022-10-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_assignment_last_updated_coding_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codinginstance',
            name='policy_id',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
