/**
 * @readonly
 * @enum {String}
 */
export const APIActionTypes = {
  GET_ASSIGNMENT_LIST: "API_GET_ASSIGNMENT_LIST",
  GET_PROJECT_SETTINGS: "API_GET_POLICY",
  GET_POLICY: "API_GET_POLICY",
  GET_POLICIES: "API_GET_POLICIES",
  GET_POLICY_INSTANCE: "API_GET_POLICY_INSTANCE",
  GET_CODING: "API_GET_CODING",
  GET_CODING_LIST: "API_GET_CODING_LIST",
  GET_CODING_PROGRESS: "API_GET_CODING_PROGRESS",
  POST_CODING_INSTANCE: "API_POST_CODING_INSTANCE",
  GET_CODING_INSTANCE: "API_GET_CODING_INSTANCE",
  AUTO_SAVE: "API_AUTO_SAVE",
  GET_ALL_CODING_INSTANCE: "API_GET_ALL_CODING_INSTANCE",
};
/**
 * @readonly
 * @enum {String}
 */
export const UserActionsTypes = {
  UPDATE_CODING: "UPDATE_CODING",
  SELECT_QUESTION: "USER_SELECT_QUESTION",
  CHANGE_VALUE: "USER_CHANGE_VALUE",
  TOGGLE_SENTENCE: "USER_TOGGLE_SENTENCE",
  CLICK_SAVE: "USER_CLICK_SAVE",
  CLICK_RESET: "USER_CLICK_RESET",
  CHANGE_QUESTION_META: "USER_CHANGE_QUESTION_META",
};
/**
 * @readonly
 * @enum {String}
 */
export const AppActionTypes = {
  SET_CURRENT_VIEW: "APP_SET_CURRENT_VIEW",
  SET_CODING_MODE: "APP_SET_MODE",
};
/**
 * @readonly
 * @enum {String}
 */
export const NULL_OP = "NULL_OP";
