
export const API_GET_POLICY = 'API_GET_POLICY';
export const API_GET_POLICIES = 'API_GET_POLICIES';
export const API_GET_POLICY_INSTANCE = 'API_GET_POLICY_INSTANCE';
export const API_GET_CODING = 'API_GET_CODING';
export const API_POST_CODING_INSTANCE = 'API_POST_CODING_INSTANCE';
export const API_GET_CODING_INSTANCE = 'API_GET_CODING_INSTANCE';

export const USER_SELECT_QUESTION = 'USER_SELECT_QUESTION';
export const USER_CHANGE_VALUE = 'USER_CHANGE_VALUE';
export const USER_TOGGLE_SENTENCE = 'USER_TOGGLE_SENTENCE';
export const USER_CLICK_SAVE = 'USER_CLICK_SAVE';
export const USER_CLICK_RESET = 'USER_CLICK_RESET';
